export type Opponent =
    | {
          type: "helicopter" | "shootingHelicopter" | "ship" | "balloon" | "plane";
          positionX: number;
          positionY: number;
          direction: -1 | 1; // left | right
          moving: boolean;
          shooting: boolean;
      }
    | {
          type: "fuel" | "bridge";
          positionX: number;
          positionY: number;
          direction: 1;
      }
    | {
          type: "tank" | "bridgeTank";
          positionX: number;
          positionY: number;
          direction: -1 | 1;
          moving: true;
          shooting: false;
          shootAt: number;
      }
    | {
          type: "bridgeTank";
          positionX: number;
          positionY: number;
          direction: -1 | 1;
          moving: true;
          shooting: false;
          shootAt: number;
      };

const opponents: Opponent[] = [
    { type: "fuel", positionX: 300, positionY: 852, direction: 1 },
    { type: "helicopter", positionX: 290, positionY: 910, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 500, positionY: 970, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 320, positionY: 1100, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 510, positionY: 1210, direction: 1, moving: false, shooting: false },
    { type: "helicopter", positionX: 410, positionY: 1290, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 370, positionY: 1420, direction: 1 },
    { type: "ship", positionX: 350, positionY: 1470, direction: -1, moving: false, shooting: false },
    { type: "helicopter", positionX: 330, positionY: 1690, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 510, positionY: 1770, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 490, positionY: 1850, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 340, positionY: 1940, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 470, positionY: 2020, direction: 1 },
    { type: "helicopter", positionX: 500, positionY: 2060, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 495, positionY: 2160, direction: 1 },
    { type: "fuel", positionX: 380, positionY: 2270, direction: 1 },
    { type: "helicopter", positionX: 320, positionY: 2320, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 480, positionY: 2380, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 465, positionY: 2480, direction: 1 },
    { type: "fuel", positionX: 330, positionY: 2550, direction: 1 },
    { type: "ship", positionX: 475, positionY: 2630, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 390, positionY: 2720, direction: 1 },
    { type: "ship", positionX: 470, positionY: 2800, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 450, positionY: 2890, direction: -1, moving: false, shooting: false },
    { type: "helicopter", positionX: 320, positionY: 2980, direction: -1, moving: false, shooting: false },
    { type: "helicopter", positionX: 420, positionY: 3100, direction: 1, moving: false, shooting: false },
    { type: "helicopter", positionX: 380, positionY: 3200, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 450, positionY: 3300, direction: 1, moving: false, shooting: false },
    { type: "helicopter", positionX: 500, positionY: 3400, direction: -1, moving: true, shooting: false },
    { type: "bridge", positionX: 402, positionY: 3524, direction: 1 },
    { type: "bridgeTank", positionX: 800, positionY: 3505, direction: -1, moving: true, shooting: false, shootAt: 390 },
    { type: "ship", positionX: 510, positionY: 3752, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 660, positionY: 3872, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 500, positionY: 3952, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 600, positionY: 4052, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 250, positionY: 4192, direction: -1, moving: false, shooting: false },
    { type: "fuel", positionX: 550, positionY: 4232, direction: 1 },
    { type: "helicopter", positionX: 180, positionY: 4282, direction: -1, moving: false, shooting: false },
    { type: "fuel", positionX: 130, positionY: 4412, direction: 1 },
    { type: "ship", positionX: 230, positionY: 4472, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 310, positionY: 4612, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 280, positionY: 4672, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 300, positionY: 4812, direction: 1, moving: false, shooting: false },
    { type: "ship", positionX: 300, positionY: 4932, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 500, positionY: 5002, direction: 1 },
    { type: "fuel", positionX: 300, positionY: 5102, direction: 1 },
    { type: "helicopter", positionX: 300, positionY: 5172, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 490, positionY: 5302, direction: 1 },
    { type: "ship", positionX: 520, positionY: 5372, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 490, positionY: 5442, direction: -1, moving: false, shooting: false },
    { type: "fuel", positionX: 550, positionY: 5532, direction: 1 },
    { type: "helicopter", positionX: 540, positionY: 5612, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 140, positionY: 5652, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 620, positionY: 5852, direction: 1 },
    { type: "fuel", positionX: 560, positionY: 5952, direction: 1 },
    { type: "helicopter", positionX: 550, positionY: 6032, direction: 1, moving: false, shooting: false },
    { type: "helicopter", positionX: 550, positionY: 6232, direction: -1, moving: false, shooting: false },
    { type: "bridge", positionX: 406, positionY: 6385, direction: 1, moving: false, shooting: false },
    { type: "bridgeTank", positionX: 20, positionY: 6366, direction: 1, moving: true, shooting: false, shootAt: 390 },
    { type: "balloon", positionX: 516, positionY: 6575, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 306, positionY: 6785, direction: 1 },
    { type: "ship", positionX: 406, positionY: 6845, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 306, positionY: 6985, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 346, positionY: 7085, direction: 1 },
    { type: "fuel", positionX: 316, positionY: 7199, direction: 1 },
    { type: "ship", positionX: 456, positionY: 7252, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 460, positionY: 7350, direction: 1 },
    { type: "balloon", positionX: 316, positionY: 7400, direction: 1, moving: false, shooting: false },
    { type: "fuel", positionX: 450, positionY: 7500, direction: 1 },
    { type: "ship", positionX: 400, positionY: 7600, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 300, positionY: 7680, direction: 1 },
    { type: "balloon", positionX: 506, positionY: 7760, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 450, positionY: 7840, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 460, positionY: 7970, direction: 1 },
    { type: "fuel", positionX: 506, positionY: 8120, direction: 1 },
    { type: "helicopter", positionX: 520, positionY: 8160, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 400, positionY: 8260, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 406, positionY: 8370, direction: 1 },
    { type: "helicopter", positionX: 510, positionY: 8490, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 440, positionY: 8640, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 310, positionY: 8720, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 400, positionY: 8800, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 430, positionY: 8880, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 490, positionY: 9060, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 406, positionY: 9120, direction: 1 },
    { type: "plane", positionX: 400, positionY: 9140, direction: -1, moving: true, shooting: false },
    { type: "bridge", positionX: 378, positionY: 9245, direction: 1 },
    { type: "bridgeTank", positionX: 20, positionY: 9226, direction: 1, moving: true, shooting: false, shootAt: 390 },
    { type: "fuel", positionX: 506, positionY: 9420, direction: 1 },
    { type: "ship", positionX: 200, positionY: 9500, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 9610, direction: -1, moving: false, shooting: false },
    { type: "ship", positionX: 330, positionY: 9690, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 586, positionY: 9760, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 500, positionY: 9820, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 9900, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 330, positionY: 10020, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 450, positionY: 10150, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 586, positionY: 10300, direction: 1 },
    { type: "plane", positionX: 400, positionY: 10375, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 140, positionY: 10450, direction: 1 },
    { type: "fuel", positionX: 590, positionY: 10580, direction: 1 },
    { type: "ship", positionX: 580, positionY: 10630, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 516, positionY: 10740, direction: 1 },
    { type: "ship", positionX: 320, positionY: 10800, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 586, positionY: 11000, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 170, positionY: 11080, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 220, positionY: 11150, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 630, positionY: 11220, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 220, positionY: 11300, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 210, positionY: 11420, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 240, positionY: 11490, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 210, positionY: 11590, direction: 1 },
    { type: "fuel", positionX: 610, positionY: 11720, direction: 1 },
    { type: "helicopter", positionX: 230, positionY: 11800, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 586, positionY: 11890, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 240, positionY: 11950, direction: -1, moving: true, shooting: false },
    { type: "bridge", positionX: 410, positionY: 12097, direction: 1 },
    { type: "bridgeTank", positionX: 20, positionY: 12078, direction: 1, moving: true, shooting: false, shootAt: 390 },
    { type: "fuel", positionX: 450, positionY: 12250, direction: 1 },
    { type: "helicopter", positionX: 290, positionY: 12340, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 400, positionY: 12430, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 290, positionY: 12500, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 390, positionY: 12580, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 420, positionY: 12750, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 500, positionY: 12810, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 486, positionY: 12920, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 400, positionY: 13000, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 400, positionY: 13120, direction: 1 },
    { type: "tank", positionX: 800, positionY: 13170, direction: -1, moving: true, shooting: false, shootAt: 500 },
    { type: "helicopter", positionX: 500, positionY: 13300, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 480, positionY: 13390, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 480, positionY: 13460, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 426, positionY: 13540, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 420, positionY: 13630, direction: 1 },
    { type: "plane", positionX: 400, positionY: 13700, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 390, positionY: 13780, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 310, positionY: 13880, direction: 1 },
    { type: "fuel", positionX: 380, positionY: 13940, direction: 1 },
    { type: "ship", positionX: 390, positionY: 14010, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 350, positionY: 14100, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 480, positionY: 14260, direction: 1 },
    { type: "plane", positionX: 700, positionY: 14360, direction: -1, moving: true, shooting: false },
    { type: "balloon", positionX: 350, positionY: 14400, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 480, positionY: 14500, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 14590, direction: 1, moving: true, shooting: false, shootAt: 400 },
    { type: "fuel", positionX: 500, positionY: 14690, direction: 1 },
    { type: "ship", positionX: 390, positionY: 14740, direction: 1, moving: true, shooting: false },
    { type: "bridge", positionX: 373, positionY: 14934, direction: 1 },
    { type: "bridgeTank", positionX: 800, positionY: 14915, direction: -1, moving: true, shooting: false, shootAt: 390 },
    { type: "ship", positionX: 390, positionY: 15020, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 250, positionY: 15090, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 370, positionY: 15230, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 230, positionY: 15300, direction: -1, moving: true, shooting: false },
    { type: "balloon", positionX: 650, positionY: 15380, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 15450, direction: 1, moving: true, shooting: false, shootAt: 230 },
    { type: "fuel", positionX: 600, positionY: 15580, direction: 1 },
    { type: "fuel", positionX: 190, positionY: 15650, direction: 1 },
    { type: "fuel", positionX: 620, positionY: 15720, direction: 1 },
    { type: "ship", positionX: 200, positionY: 15740, direction: 1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 640, positionY: 15830, direction: 1, moving: true, shooting: true },
    { type: "fuel", positionX: 250, positionY: 15860, direction: 1 },
    { type: "fuel", positionX: 650, positionY: 15960, direction: 1 },
    { type: "ship", positionX: 630, positionY: 15990, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 210, positionY: 16100, direction: 1 },
    { type: "helicopter", positionX: 230, positionY: 16160, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 700, positionY: 16240, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 16350, direction: -1, moving: true, shooting: false, shootAt: 660 },
    { type: "helicopter", positionX: 230, positionY: 16460, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 630, positionY: 16540, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 230, positionY: 16600, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 330, positionY: 16680, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 350, positionY: 16800, direction: 1 },
    { type: "fuel", positionX: 450, positionY: 16900, direction: 1 },
    { type: "fuel", positionX: 530, positionY: 16980, direction: 1 },
    { type: "balloon", positionX: 250, positionY: 17020, direction: 1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 640, positionY: 17140, direction: 1, moving: true, shooting: true },
    { type: "helicopter", positionX: 250, positionY: 17280, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 300, positionY: 17430, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 530, positionY: 17500, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 700, positionY: 17590, direction: 1, moving: true, shooting: false },
    { type: "bridge", positionX: 363, positionY: 17766, direction: 1 },
    { type: "bridgeTank", positionX: 800, positionY: 17747, direction: -1, moving: true, shooting: false, shootAt: 390 },
    { type: "plane", positionX: 700, positionY: 17920, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 330, positionY: 18080, direction: 1 },
    { type: "ship", positionX: 490, positionY: 18140, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 510, positionY: 18200, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 500, positionY: 18260, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 18300, direction: -1, moving: true, shooting: false, shootAt: 360 },
    { type: "helicopter", positionX: 350, positionY: 18320, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 400, positionY: 18460, direction: 1 },
    { type: "plane", positionX: 200, positionY: 18500, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 500, positionY: 18600, direction: 1 },
    { type: "plane", positionX: 350, positionY: 18640, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 18700, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 400, positionY: 18840, direction: 1 },
    { type: "tank", positionX: 0, positionY: 18870, direction: 1, moving: true, shooting: false, shootAt: 330 },
    { type: "shootingHelicopter", positionX: 520, positionY: 18930, direction: -1, moving: true, shooting: true },
    { type: "ship", positionX: 400, positionY: 19000, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 420, positionY: 19050, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 380, positionY: 19120, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 320, positionY: 19200, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 500, positionY: 19300, direction: 1 },
    { type: "tank", positionX: 0, positionY: 19340, direction: 1, moving: true, shooting: false, shootAt: 250 },
    { type: "plane", positionX: 350, positionY: 19420, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 510, positionY: 19520, direction: 1 },
    { type: "ship", positionX: 320, positionY: 19540, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 19620, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 310, positionY: 19720, direction: 1 },
    { type: "shootingHelicopter", positionX: 480, positionY: 19790, direction: -1, moving: true, shooting: true },
    { type: "ship", positionX: 320, positionY: 19840, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 19870, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 360, positionY: 19920, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 19960, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 20000, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 20040, direction: -1, moving: true, shooting: false, shootAt: 400 },
    { type: "tank", positionX: 0, positionY: 20090, direction: 1, moving: true, shooting: false, shootAt: 300 },
    { type: "helicopter", positionX: 320, positionY: 20160, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 420, positionY: 20280, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 20400, direction: -1, moving: true, shooting: false },
    { type: "bridge", positionX: 426, positionY: 20622, direction: 1 },
    { type: "bridgeTank", positionX: 800, positionY: 20603, direction: -1, moving: true, shooting: false, shootAt: 390 },
    { type: "helicopter", positionX: 320, positionY: 20740, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 500, positionY: 20820, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 20940, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 460, positionY: 21020, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 480, positionY: 21150, direction: 1 },
    { type: "plane", positionX: 350, positionY: 21200, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 21260, direction: 1, moving: true, shooting: false, shootAt: 400 },
    { type: "ship", positionX: 400, positionY: 21320, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 530, positionY: 21420, direction: 1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 270, positionY: 21460, direction: -1, moving: true, shooting: true },
    { type: "helicopter", positionX: 540, positionY: 21500, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 520, positionY: 21550, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 170, positionY: 21620, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 150, positionY: 21740, direction: 1 },
    { type: "ship", positionX: 520, positionY: 21780, direction: -1, moving: true, shooting: false },
    { type: "balloon", positionX: 420, positionY: 21860, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 21900, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 500, positionY: 21960, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 22020, direction: -1, moving: true, shooting: false, shootAt: 400 },
    { type: "shootingHelicopter", positionX: 270, positionY: 22120, direction: 1, moving: true, shooting: true },
    { type: "helicopter", positionX: 190, positionY: 22200, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 200, positionY: 22260, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 22300, direction: -1, moving: true, shooting: false, shootAt: 200 },
    { type: "fuel", positionX: 650, positionY: 22440, direction: 1 },
    { type: "ship", positionX: 200, positionY: 22490, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 190, positionY: 22560, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 220, positionY: 22620, direction: -1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 570, positionY: 22630, direction: 1, moving: true, shooting: true },
    { type: "fuel", positionX: 550, positionY: 22740, direction: 1 },
    { type: "helicopter", positionX: 450, positionY: 22800, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 370, positionY: 22890, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 410, positionY: 22960, direction: -1, moving: true, shooting: false },
    { type: "balloon", positionX: 360, positionY: 23040, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 23120, direction: 1, moving: true, shooting: false, shootAt: 200 },
    { type: "helicopter", positionX: 490, positionY: 23200, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 23300, direction: 1, moving: true, shooting: false },
    { type: "bridge", positionX: 442, positionY: 23474, direction: 1 },
    { type: "bridgeTank", positionX: 20, positionY: 23455, direction: 1, moving: true, shooting: false, shootAt: 390 },
    { type: "fuel", positionX: 510, positionY: 23630, direction: 1 },
    { type: "helicopter", positionX: 490, positionY: 23660, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 280, positionY: 23700, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 350, positionY: 23760, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 650, positionY: 23820, direction: -1, moving: true, shooting: false },
    { type: "balloon", positionX: 435, positionY: 23900, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 23950, direction: 1, moving: true, shooting: false, shootAt: 380 },
    { type: "fuel", positionX: 490, positionY: 23960, direction: 1 },
    { type: "fuel", positionX: 320, positionY: 24070, direction: 1 },
    { type: "fuel", positionX: 480, positionY: 24140, direction: 1 },
    { type: "shootingHelicopter", positionX: 570, positionY: 24210, direction: -1, moving: true, shooting: true },
    { type: "plane", positionX: 0, positionY: 24300, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 480, positionY: 24370, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 380, positionY: 24490, direction: 1 },
    { type: "ship", positionX: 320, positionY: 24550, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 24550, direction: 1, moving: true, shooting: false, shootAt: 400 },
    { type: "fuel", positionX: 360, positionY: 24640, direction: 1 },
    { type: "shootingHelicopter", positionX: 470, positionY: 24720, direction: -1, moving: true, shooting: true },
    { type: "fuel", positionX: 320, positionY: 24870, direction: 1 },
    { type: "fuel", positionX: 400, positionY: 24940, direction: 1 },
    { type: "fuel", positionX: 350, positionY: 25000, direction: 1 },
    { type: "tank", positionX: 0, positionY: 25010, direction: 1, moving: true, shooting: false, shootAt: 460 },
    { type: "fuel", positionX: 480, positionY: 25100, direction: 1 },
    { type: "ship", positionX: 420, positionY: 25200, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 380, positionY: 25300, direction: 1 },
    { type: "helicopter", positionX: 490, positionY: 25340, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 340, positionY: 25430, direction: 1 },
    { type: "fuel", positionX: 320, positionY: 25500, direction: 1 },
    { type: "plane", positionX: 0, positionY: 25580, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 380, positionY: 25670, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 480, positionY: 25760, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 25800, direction: -1, moving: true, shooting: false, shootAt: 500 },
    { type: "shootingHelicopter", positionX: 370, positionY: 25960, direction: 1, moving: true, shooting: true },
    { type: "fuel", positionX: 420, positionY: 26100, direction: 1 },
    { type: "plane", positionX: 0, positionY: 26200, direction: -1, moving: true, shooting: false },
    { type: "bridge", positionX: 433, positionY: 26326, direction: 1 },
    { type: "bridgeTank", positionX: 20, positionY: 26307, direction: 1, moving: true, shooting: false, shootAt: 390 },
    { type: "ship", positionX: 520, positionY: 26400, direction: -1, moving: true, shooting: false },
    { type: "ship", positionX: 250, positionY: 26480, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 500, positionY: 26560, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 410, positionY: 26620, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 0, positionY: 26660, direction: -1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 320, positionY: 26760, direction: 1, moving: true, shooting: true },
    { type: "plane", positionX: 0, positionY: 26820, direction: 1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 26880, direction: -1, moving: true, shooting: false, shootAt: 460 },
    { type: "ship", positionX: 460, positionY: 26920, direction: -1, moving: true, shooting: false },
    { type: "fuel", positionX: 410, positionY: 27050, direction: 1 },
    { type: "plane", positionX: 230, positionY: 27100, direction: -1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 370, positionY: 27160, direction: -1, moving: true, shooting: true },
    { type: "helicopter", positionX: 410, positionY: 27220, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 450, positionY: 27300, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 230, positionY: 27370, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 400, positionY: 27430, direction: 1, moving: true, shooting: false },
    { type: "ship", positionX: 410, positionY: 27500, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 0, positionY: 27540, direction: 1, moving: true, shooting: false, shootAt: 410 },
    { type: "fuel", positionX: 510, positionY: 27630, direction: 1 },
    { type: "ship", positionX: 310, positionY: 27660, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 300, positionY: 27730, direction: 1, moving: true, shooting: false },
    { type: "balloon", positionX: 535, positionY: 27800, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 660, positionY: 27860, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 230, positionY: 27920, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 670, positionY: 28020, direction: 1 },
    { type: "shootingHelicopter", positionX: 270, positionY: 28060, direction: 1, moving: true, shooting: true },
    { type: "fuel", positionX: 450, positionY: 28100, direction: 1 },
    { type: "tank", positionX: 0, positionY: 28110, direction: 1, moving: true, shooting: false, shootAt: 180 },
    { type: "ship", positionX: 280, positionY: 28120, direction: -1, moving: true, shooting: false },
    { type: "helicopter", positionX: 660, positionY: 28200, direction: 1, moving: true, shooting: false },
    { type: "helicopter", positionX: 100, positionY: 28220, direction: 1, moving: true, shooting: false },
    { type: "fuel", positionX: 100, positionY: 28340, direction: 1 },
    { type: "tank", positionX: 400, positionY: 28360, direction: 1, moving: true, shooting: false, shootAt: 640 },
    { type: "tank", positionX: 400, positionY: 28460, direction: -1, moving: true, shooting: false, shootAt: 240 },
    { type: "balloon", positionX: 305, positionY: 28480, direction: -1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 670, positionY: 28500, direction: 1, moving: true, shooting: true },
    { type: "plane", positionX: 230, positionY: 28600, direction: 1, moving: true, shooting: false },
    { type: "plane", positionX: 330, positionY: 28670, direction: -1, moving: true, shooting: false },
    { type: "plane", positionX: 730, positionY: 28720, direction: 1, moving: true, shooting: false },
    { type: "shootingHelicopter", positionX: 370, positionY: 28800, direction: 1, moving: true, shooting: true },
    { type: "tank", positionX: 0, positionY: 28860, direction: 1, moving: true, shooting: false, shootAt: 340 },
    { type: "tank", positionX: 800, positionY: 28860, direction: -1, moving: true, shooting: false, shootAt: 540 },
    { type: "ship", positionX: 480, positionY: 28920, direction: -1, moving: true, shooting: false },
    { type: "tank", positionX: 800, positionY: 28960, direction: -1, moving: true, shooting: false, shootAt: 400 },
    { type: "plane", positionX: 330, positionY: 29000, direction: -1, moving: true, shooting: false },
];

export default opponents;
